// Authoritative PetalPal Month Region Data (1200x900 spatial grid, scale=2 for 2400x1800 world)
// Auto-generated from authoritative Reference A (Structure Map) and Reference B (Planting Mask).
// Strictly excludes non-grass surfaces (courtyards, moon bed, paths, water, rocks).
// Do not edit manually.

export const GARDEN_WORLD_WIDTH = 2400;
export const GARDEN_WORLD_HEIGHT = 1800;

export const REGION_GRID_WIDTH = 1200;
export const REGION_GRID_HEIGHT = 900;
export const REGION_GRID_SCALE = 2;

export interface MonthRegionMeta {
  month: number;
  landId: string;
  monthName: string;
  label: string;
  centroid: { x: number; y: number };
  bbox: { x: number; y: number; width: number; height: number };
  pixelArea: number;
}

export const MONTH_CENTROIDS: Record<number, { x: number; y: number }> = {
  "1": {
    "x": 1200.0,
    "y": 562.0
  },
  "2": {
    "x": 952.0,
    "y": 742.0
  },
  "3": {
    "x": 1338.0,
    "y": 854.0
  },
  "4": {
    "x": 1386.0,
    "y": 208.0
  },
  "5": {
    "x": 1524.0,
    "y": 352.0
  },
  "6": {
    "x": 1838.0,
    "y": 320.0
  },
  "7": {
    "x": 2166.0,
    "y": 794.0
  },
  "8": {
    "x": 1994.0,
    "y": 1372.0
  },
  "9": {
    "x": 1166.0,
    "y": 1332.0
  },
  "10": {
    "x": 544.0,
    "y": 1116.0
  },
  "11": {
    "x": 460.0,
    "y": 872.0
  },
  "12": {
    "x": 404.0,
    "y": 604.0
  }
};

export const MONTH_REGION_METAS: Record<number, MonthRegionMeta> = {
  "1": {
    "month": 1,
    "landId": "Land01",
    "monthName": "January",
    "label": "Land01 (January)",
    "centroid": {
      "x": 1200.0,
      "y": 562.0
    },
    "bbox": {
      "x": 982,
      "y": 490,
      "width": 356,
      "height": 162
    },
    "pixelArea": 37224
  },
  "2": {
    "month": 2,
    "landId": "Land02",
    "monthName": "February",
    "label": "Land02 (February)",
    "centroid": {
      "x": 952.0,
      "y": 742.0
    },
    "bbox": {
      "x": 882,
      "y": 626,
      "width": 248,
      "height": 348
    },
    "pixelArea": 38372
  },
  "3": {
    "month": 3,
    "landId": "Land03",
    "monthName": "March",
    "label": "Land03 (March)",
    "centroid": {
      "x": 1338.0,
      "y": 854.0
    },
    "bbox": {
      "x": 1192,
      "y": 636,
      "width": 240,
      "height": 348
    },
    "pixelArea": 40044
  },
  "4": {
    "month": 4,
    "landId": "Land04",
    "monthName": "April",
    "label": "Land04 (April)",
    "centroid": {
      "x": 1386.0,
      "y": 208.0
    },
    "bbox": {
      "x": 1186,
      "y": 114,
      "width": 364,
      "height": 304
    },
    "pixelArea": 51140
  },
  "5": {
    "month": 5,
    "landId": "Land05",
    "monthName": "May",
    "label": "Land05 (May)",
    "centroid": {
      "x": 1524.0,
      "y": 352.0
    },
    "bbox": {
      "x": 1424,
      "y": 218,
      "width": 214,
      "height": 298
    },
    "pixelArea": 33048
  },
  "6": {
    "month": 6,
    "landId": "Land06",
    "monthName": "June",
    "label": "Land06 (June)",
    "centroid": {
      "x": 1838.0,
      "y": 320.0
    },
    "bbox": {
      "x": 1708,
      "y": 278,
      "width": 374,
      "height": 172
    },
    "pixelArea": 20352
  },
  "7": {
    "month": 7,
    "landId": "Land07",
    "monthName": "July",
    "label": "Land07 (July)",
    "centroid": {
      "x": 2166.0,
      "y": 794.0
    },
    "bbox": {
      "x": 1770,
      "y": 626,
      "width": 544,
      "height": 324
    },
    "pixelArea": 82388
  },
  "8": {
    "month": 8,
    "landId": "Land08",
    "monthName": "August",
    "label": "Land08 (August)",
    "centroid": {
      "x": 1994.0,
      "y": 1372.0
    },
    "bbox": {
      "x": 1786,
      "y": 1190,
      "width": 398,
      "height": 338
    },
    "pixelArea": 87668
  },
  "9": {
    "month": 9,
    "landId": "Land09",
    "monthName": "September",
    "label": "Land09 (September)",
    "centroid": {
      "x": 1166.0,
      "y": 1332.0
    },
    "bbox": {
      "x": 1034,
      "y": 1096,
      "width": 328,
      "height": 428
    },
    "pixelArea": 76712
  },
  "10": {
    "month": 10,
    "landId": "Land10",
    "monthName": "October",
    "label": "Land10 (October)",
    "centroid": {
      "x": 544.0,
      "y": 1116.0
    },
    "bbox": {
      "x": 264,
      "y": 874,
      "width": 532,
      "height": 420
    },
    "pixelArea": 106700
  },
  "11": {
    "month": 11,
    "landId": "Land11",
    "monthName": "November",
    "label": "Land11 (November)",
    "centroid": {
      "x": 460.0,
      "y": 872.0
    },
    "bbox": {
      "x": 142,
      "y": 748,
      "width": 570,
      "height": 370
    },
    "pixelArea": 100208
  },
  "12": {
    "month": 12,
    "landId": "Land12",
    "monthName": "December",
    "label": "Land12 (December)",
    "centroid": {
      "x": 404.0,
      "y": 604.0
    },
    "bbox": {
      "x": 160,
      "y": 478,
      "width": 568,
      "height": 314
    },
    "pixelArea": 89136
  }
};

// Compact Little-Endian Uint16 RLE byte array encoded in Base64
// Format: [val (1 byte), count_low (1 byte), count_high (1 byte)]
const RLE_BASE64 = "AP//AO8NBBwAAJQEBBwAAI0EBCoAAIEEBDUAAHcEBD4AAG4EBEUAAGgEBEsAAGEEBDsAAAUABBEAAF8EBDsAAAUABBEAAF0EBDoAAAoABBEAAFcEBDwAAA8ABBEAAFIEBDwAABMABBEAAE0EBD0AABUABBMAAEgEBEAAABcABAQAAAMABAsAAEYEBEAAABkABAIAAAUABAwAAEQEBEAAABkABAIAAAUABAwAAEEEBEIAABoABAEAAAcABAwAAD4EBEMAACQABAwAADsEBEQAACUABA0AADcEBEcAACUABA4AADUEBEgAACUABA4AADUEBEgAACUABA4AADMEBEoAACYABA4AADAEBEwAACgABAwAAC4EBE8AACgABAsAACwEBFEAACkABAoAACsEBFIAACkABAwAACgEBFQAACgABAoAACoEBFQAACgABAoAACgEBFcAACcABAoAACYEBFoAACYABAoAACUEBF4AACIABAsAACQEBGMAAAkABAIAABMABAsAACMEBG8AABMABAoAACEEBHMAABEABAsAACEEBHMAABEABAsAACAEBHgAAAoABA0AACAEBHsAAAYABA4AACAEBJAAAB8EBAoAAAUABIEAAB4EBAoAAAkABH4AAB4EBAoAAA0ABHkAACAEBAoAAA0ABHkAAB8EBAcAABMABHYAAB8EBAcAABUABHUAAB4EBAcAABYABHMAAB8EBAgAABcABHEAAB4EBAkAABgABHEAAB0EBAUAAB4ABG0AACAEBAUAAB4ABG0AAB8EBAQAACAABGwAAB8EBAMAACQABGkAAB8EBAMAACUABGgAACcABQkAAO8DBAMAACYABGYAACYABQ4AAOsDBAQAACcABGQAACYABREAAOoDBAQAACUABGQAACcABRQAAOgDBAQAACUABGQAACcABRQAAOcDBAQAACYABGMAACYABRcAAOUDBAUAACYABGAAACgABRkAAOMDBAcAACQABGAAACgABRsAAOEDBAgAACMABF8AACkABRwAAOEDBAgAACIABF4AACoABR4AAOADBAgAACIABF4AACoABR4AAN8DBAoAAB0ABF8AACwABR8AAN0DBAwAABIABAIAAAcABF8AACwABSIAANsDBA8AAA0ABGkAAC0ABSMAANsDBBMAAAcABGgAAC8ABSYAANgDBIEAADAABRwAAAIABQkAANgDBH8AADAABRwAAAcABQYAANgDBH8AADAABRwAAAcABQYAANcDBH0AADEABR0AAAkABQYAANYDBHsAADIABRsAAA4ABQQAANUDBHoAADMABRsAABAABQMAANUDBHcAADUABRsAABMABQEAANMDBHcAADUABR0AABMABQIAANIDBHYAADQABR4AABQABQIAANIDBHYAADQABR4AABQABQIAANEDBHQAADYABR4AABUABQIAANEDBHMAADUABR4AABgABQEAANEDBHEAADUABSAAABgABQEAANADBHEAADQABSIAAOkDBG8AADQABSQAABkABQEAAM8DBG4AADMABSYAABgABQIAAHYABhIAAEcDBG4AADMABSYAABgABQIAAHYABhIAAEYDBG4AADMABScAABgABQIAAG4ABiMAAD0DBG0AADEABSwAABUABQMAAGcABjAAADcDBGwAADAABS4AABUABQMAAGMABjkAADIDBGsAAC0ABTQAABMABQIAAF8ABkMAAC0DBGkAAC0ABTcAABAABQQAAFsABkoAACoDBGgAACwABT0AAAsABQUAAFkABk8AACcDBGgAACwABT0AAAsABQUAAFkABk8AACcDBGgAACkABUIAAAYABQgAAFYABlUAACQDBGcAACgABVIAAFIABlsAACIDBGYAACcABVQAAFAABmEAAB4DBGYAACQABVYAAE4ABmUAAB0DBGUAACMABVgAAEwABmkAABsDBGUAACMABVgAAEwABmkAABsDBGUAACEABVoAAEoABm4AABgDBA4AAAgABE4AACAABVwAAEcABmcAAAcABgUAABYDBA0AAA0ABEoAAB8ABVwAAEYABgMAAAcABl4AAAoABgUAABUDBAgAABIABEkAAB0ABV4AAEUABgMAAAsABloAAA4ABgQAABMDBAgAABIABEcAAB8ABV4AAEIABgUAAA4ABlUAABMABgQAABEDBAcAABQABEYAAB4ABV0AAEMABgUAAA8ABlMAABgABgIAABADBAcAABQABEYAAB4ABV0AAEMABgUAAA8ABlMAABgABgIAABEDBAYAABQABEYAAB0ABV4AAEEABgMAABMABlIAABkABgQAAA8DBAUAABYABEUAAB0ABV4AAEAABgMAABUABlEAABoABgUAAA4DBAMAABgABEMAABwABV8AAD4ABgYAABcABk8AABoABgYAAA0DBAMAABoABEEAABwABV8AAD0ABgcAABgABkwAAB0ABgcAAAsDBAMAABoABEEAABsABV8AAD0ABgYAABoABkwAAB4ABgcAAAwDBAEAABoABEEAABsABV4AAD0ABgcAABoABksAAB8ABgkAAAoDBAEAABoABEEAABsABV4AAD0ABgcAABoABksAAB8ABgkAACUDBEEAABsABV4AADwABgcAABoABkwAAB8ABgoAACQDBEEAABsABV0AADwABggAABoABkwAAB8ABgwAACADBEMAABsABV0AADoABgsAABkABk0AAB0ABg4AAB8DBEMAABsABVwAADoABgwAABcABiYAABMABhYAAB0ABg8AACADBEEAABsABVoAADsABg0AABcABh8AACEABg8AAB0ABg8AACADBEIAABoABVkAADsABg4AABUABhwAACkABgwAABwABhIAAB4DBEIAABoABVkAADsABg4AABUABhwAACkABgwAABwABhIAAB4DBEIAABoABVgAADsABhAAABAABh0AADEABggAABoABhQAABsDBEQAABsABVYAADwABhIAAA0ABhsAADYABggAABQABhkAABoDBCkAAAUABBYAABsABVUAADsABhoAAAUABhsAADsABgkAAAYABgMAAAUABhwAABgDBCgAAAkABBYAABkABVUAADoABigAAAQABg0AAD8ABjIAABUDBCcAAA4ABBQAABsABVIAADsABicAAAcABggAAEQABgwAAAIABiIAAAwDBAMAAAIABCgAABMABBIAABsABVAAADwABicAAA0ABgEAAEkABgMAAAkABiIAAAsDBAMAAAIABCgAABMABBIAABsABVAAADwABicAAA0ABgEAAEkABgMAAAkABiIAAAwDBCsAABYABBAAABsABU8AADwABgsAAAcABhYAAFgABgEAAAwABiIAAAwDBCkAABgABA8AABsABU0AAD0ABgkAAAsABhMAAGYABiIAAA0DBCcAABoABA4AABsABUwAAD0ABgcAABAABhEAAGcABiIAAA0DBCQAABwABA4AABsABUsAAD4ABgYAABIABg4AAGoABiEAABADBB8AAB8ABA4AABsABUkAAD4ABgUAABYABgsAAGsABiIAABADBB0AACAABA4AABsABUcAAEAABgUAABcABgoAAGwABiEAABADBB0AACAABA4AABsABUcAAEAABgUAABcABgoAAGwABiEAABIDBBsAACEABA0AABsABUcAAEAABgQAABgABgkAAG4ABiEAABQDBBgAACIABAwAABwABUUAAD8ABgUAABoABggAAG8ABiAAABYDBBYAACIABAwAABwABUQAAEAABgQAABsABggAAG8ABiEAABcDBBQAACMABAsAABwABUQAAEAABgQAABwABgcAAG4ABiIAABoDBBEAACMABAsAABwABUMAAEEABgQAABwABggAAG0ABiIAABoDBBEAACMABAsAABwABUMAAEEABgQAABwABggAAG0ABiIAABwDBA8AACIABAwAABwABUIAAEEABgUAABwABggAAG0ABiMAAB0DBA0AACIABAwAABwABUIAAEEABgUAABwABggAAGwABiQAACADBAsAACEABAwAABwABUAAAEMABgQAABwABgkAAGwABiQAACIDBAsAAB8ABAwAABwABUAAAEMABgMAAB0ABgkAAGwABiQAACYDBAgAAB0ABAwAAB0ABT8AAEQABgMAAB0ABgkAAGwABiYAACYDBAgAABsABAwAAB0ABT8AAEQABgMAAB0ABgkAAGwABiYAACYDBAgAABsABAwAAB0ABT8AAEQABgMAAB0ABgkAAGwABiYAACkDBAYAABkABAwAAB4ABT4AAEUABgEAAB4ABgoAAGsABhYAAAUABgwAAC0DBAoAAA8ABAwAACAABT4AAGMABgoAAGwABhQAAAkABgoAADADBAoAAAYABBEAACEABT4AAF8ABg0AAG4ABhEAAA4ABgcAADQDBBwAACIABT4AAF4ABg4AAG4ABg4AABIABgYAADkDBBUAACMABT4AAFoABhIAAG8ABg4AABMABgUAAD4DBAwAACcABT4AAFoABhEAAHEABgwAABQABgUAAD4DBAwAACcABT4AAFoABhEAAHEABgwAABQABgUAAHADBT8AAEoABgQAAAoABhAAAHQABgsAABYABgQAAHADBT8AAEsABgYAAAUABhEAAHYABgkAABgABgMAAHADBT8AAE0ABhgAAHgABgkAABgABgMAAG8DBUAAAE4ABhYAAHsABgcAABgABgMAAG8DBT8AAFMABg8AAH4ABgcAABgABgMAAG0DBUEAAFkABgMAAIUABgYAABgABgMAAG0DBUEAAFkABgMAAIUABgYAABgABgMAAG0DBUEAAOIABgUAABgABgEAAG4DBSwAAAcABQ8AAOIABgUAABcABgIAAG0DBSoAAAwABQ4AAOIABgUAABYABgIAAG0DBScAABEABQwAAOMABgQAABYABgEAAG0DBScAABMABQsAAOQABgUAABQABgEAAG0DBScAABUABQkAAOcABgcAAH0DBScAABUABQkAAOcABgcAAHwDBSYAABcABQkAAOkABgYAAAUABgIAAHQDBSUAABkABQgAAO0ABg0AAG4DBSYAABsABQcAAGgEBSUAABwABQcAAGgEBSQAAB4ABQYAAGgEBSQAAB4ABQYAAGgEBSQAAB4ABQYAAGgEBSQAAB4ABQYAAGgEBSQAAB4ABQcAAGcEBSQAACAABQQAAGgEBSQAACAABQQAAGgEBSQAACAABQQAAGgEBSQAACAABQQAAGoEBSIAACAABQQAAGoEBSMAAB8ABQQAAGsEBSMAAB4ABQQAAFMCDBAAAAgCBSQAAB0ABQMAAE4CDBsAAAQCBSIAAB4ABQMAAEoCDCQAAAACBSEAAB4ABQMAAEoCDCQAAAACBSEAAB4ABQMAAEYCDC0AAPwBBR8AAB4ABQMAAEQCDDMAAPsBBR0AAB4ABQMAAEECDDoAAFsBAR8AAH4ABRwAAB0ABQIAAEACDD8AAFIBAS0AAHgABRsAAB0ABQEAAD8CDAQAAAgADDkAAEgBATgAAHQABRoAABwABQIAADwCDAYAAAsADDkAAEEBAUMAAG8ABRkAABoABQMAAD0CDAYAAAsADDkAAEEBAUMAAG8ABRkAABoABQMAADsCDAYAABAADDgAADwBAUkAAG8ABRcAABcABQQAADkCDAYAABQADDoAADQBAVIAAGwABRcAABMABQYAADkCDAYAABYADDsAADABAVcAAGsABRYAAAoABQEAAAUABQUAADoCDAcAABkADDsAACoBAV8AAGkABRgAAAIABQ0AADsCDAcAABoADD4AACUBAWMAAGoABSMAADkCDAoAABoADEAAACABAWkAAGoABRsAAD4CDAoAABoADEAAACABAWkAAGoABRsAADwCDAsAABwADEEAABsBAW8AAGwABRMAAD4CDAcAACEADEMAABgBAXEAALsCDAYAACQADEQAABMBAXcAALUCDAcAACYADEYAAA8BAXsAALICDAcAACcADEcAAAwBAX8AALACDAcAACcADEcAAAwBAX8AAK8CDAgAACcADEoAAAYBAYUAAKsCDAgAACgADEwAAAMBAYcAAKkCDAgAACkADE0AAAABAYsAAKYCDAkAACgADFEAAPwAAQUAAAUAAYMAAKMCDAoAACkADFIAAPgAAQUAAAwAAYEAAJ8CDA0AACgADFQAAPUAAQUAAA4AAYIAAJ0CDA0AACgADFQAAPUAAQUAAA4AAYIAAJwCDA4AACcADFYAAPMAAQUAAA8AAYMAAJoCDA8AACUADFoAAPAAAQYAABAAAXsAAAIAAQcAAJcCDBAAACMADF4AAOsAAQQAABYAAXcAAAgAAQYAAJUCDBEAABIADAEAAAoADGQAAOkAAQMAABgAAXUAAA4AAQMAAJICDBQAABAADAUAAAUADGgAAOYAAQIAABsAAXIAABIAAQIAAJACDBkAAAgADHgAAOMAAQIAABwAAXEAABQAAQIAAI8CDBkAAAgADHgAAOMAAQIAABwAAXEAABQAAQIAAI4CDJsAAOEAAQMAABwAAXAAABUAAQMAAIwCDJ4AAN4AAQMAAB0AAXAAABUAAQQAAIoCDKAAANsAAQUAABwAAW8AABgAAQUAAIYCDKMAANoAAQQAAB0AAW4AABoAAQUAAIUCDKYAANYAAQUAAB0AAW4AABsAAQQAAIQCDKgAANUAAQUAABsAAXAAABsAAQUAAIMCDKgAANUAAQUAABsAAXAAABsAAQUAAIICDKoAANMAAQYAABoAAXAAABwAAQUAAIECDK0AANEAAQcAABYAAXQAABoAAQcAAH8CDLAAAM8AAQcAABYAAXQAABoAAQcAAH8CDLEAAM4AAQcAABUAAXUAABoAAQcAAH4CDLMAAM0AAQgAABMAAXYAABkAAQgAAHwCDLYAAMwAAQgAABIAAXgAABcAAQkAAHwCDLYAAMwAAQgAABIAAXgAABcAAQkAAHwCDLgAAMoAAQ0AAAkAAX4AABQAAQoAAHsCDLsAAMkAAQ4AAAUAAYEAAA8AAQ4AAHoCDL0AAMgAAZkAAAgAAQ8AAHsCDL4AAMcAAZsAAAMAARIAAHoCDMAAAMcAAa4AAHoCDMIAAMgAAasAAHsCDMIAAMgAAasAAHsCDMUAAMYAAVQAAAEAAVUAAHoCDMcAAMYAAVIAAAMAAVEAAH0CDMgAAMYAAVAAAAQAAVAAAHwCDMsAAMYAAU8AAAQAAU8AAH0CDMwAAMYAAU4AAAQAAU4AAH4CDMwAAMYAAU4AAAQAAU4AAH0CDM8AAMcAAUsAAAQAAUsAAIACDNAAAMcAAUkAAAcAAUgAAIACDNIAAMcAAUgAAAcAAUYAAIICDNMAAMgAAUYAAAcAAUUAAIICDNYAAMgAAUQAAAcAAUIAAIUCDNgAAMgAAUIAAAcAAUAAAIcCDNgAAMgAAUIAAAcAAUAAAIYCDNoAAMgAAT8AAAoAAT4AAIcCDNsAAMgAAT4AAAoAATwAAIgCDN0AAJoAAgkAACcAASMAAAQAARMAAAwAARMAAAIAASQAAMcBBwgAAAQABwMAALQADN4AAJYAAg4AACcAASEAAAQAARMAAAwAARIAAAQAASEAAMcBBwgAAAgABwUAAK4ADOEAAJMAAhMAACUAASAAAAQAAQ8AABUAAQ0AAAQAASAAAMcBBwUAABAABwMAAKwADMIAAAEADCAAAJAAAhYAACUAAR8AAAUAAQcAAB8AAQcAAAUAAR4AAMcBBwcAABIABwQAAKoADMIAAAEADCAAAJAAAhYAACUAAR8AAAUAAQcAAB8AAQcAAAUAAR4AAMcBBwcAABIABwQAAKkADL8AAAgADB4AAI4AAhgAACcAARwAADAAAQEAAAYAARwAAC8AAwcAAJIBBwcAABQABwYAAKYADL4AAAwADBwAAIsAAhwAACYAARsAADcAARoAACwAAxAAAI4BBwcAABUABwYAAKUADLsAABEADBsAAIkAAh8AACYAARkAADcAARkAACsAAxMAAIwBBwcAABYABwgAAKIADLoAABUADBsAAIYAAiIAACcAARYAADcAARYAACwAAxYAAIoBBwYAABkABwkAAKAADLkAABgADBsAAIMAAiUAACYAARMAADsAARIAACsAAxQAAAQAAwIAAIcBBwYAABsABwoAAJ4ADLoAABkADBsAAIIAAicAACYAAQ0AAEMAAQoAAC0AAxQAAI8BBwYAABwABwoAAJ0ADLoAABkADBsAAIIAAicAACYAAQ0AAEMAAQoAAC0AAxQAAI8BBwYAABwABwoAAJ0ADLkAABoADBwAAIAAAiIAADAAAQYAAHsAAxUAAI8BBwcAABwABwsAAJwADLgAABsADB0AAH8AAh8AALIAAxYAAJABBwcAABwABwwAAJoADLgAAB0ADB0AAH0AAiAAALAAAxgAAI8BBwgAABwABw0AAJkADLcAAB8ADB0AAHoAAiEAAK8AAxoAAI8BBwgAABsABxAAAJcADLcAACAADB4AAHgAAiEAAK4AAxgAAJEBBwkAABsABxEAAJUADLYAACIADB8AAHYAAiMAABIAAgEAAJcAAxoAAJIBBwsAABkABxIAAJQADLYAACIADB8AAHYAAiMAABIAAgEAAJcAAxoAAJIBBwsAABkABxIAAJQADLYAACQADB4AAHUAAiEAABQAAgMAAJQAAxoAAJIBBwwAABgABxQAAJMADLYAACQADB8AAHMAAiEAABYAAgQAAJAAAxwAAJIBBw0AABYABxUAAJEADLgAACQADCIAAHAAAiEAABYAAgUAAIwAAx4AAJMBBxAAABIABxcAAJAADLcAACMADCUAAG4AAiEAABsAAgMAAIgAAx8AABkAAwEAAHkBBxUAAAcABx8AAI8ADLcAACMADCYAAG0AAiEAAB0AAgIAAIYAAyAAABkAAwEAAHkBBz0AAI0ADLcAACMADCYAAG0AAiEAAB0AAgIAAIYAAyAAABkAAwEAAHkBBz0AAIwADLcAACMADCgAAGwAAiEAAB4AAgQAAIEAAyIAABkAAwMAAHUBBz8AAIwADLcAACMADCkAAGoAAiMAAB8AAgMAAH0AAyYAABgAAwMAAHUBB0AAAIsADLcAACMADCoAAGkAAiMAACEAAgEAAHwAAycAABgAAwQAAHMBB0EAAIsADLgAACIADCwAAGUAAiUAACEAAgIAAHoAAykAABYAAwUAAHMBB0IAAIkADLkAACEADC4AAGQAAiYAACAAAgMAAHgAAysAABQAAwcAAHEBB0MAAIkADLkAAB8ADDEAAGMAAicAACAAAgIAAHYAAy4AABIAAwgAAHEBB0QAAIgADLkAAB8ADDEAAGMAAicAACAAAgIAAHYAAy4AABIAAwgAAHEBB0QAAIgADLoAABkADDcAAGEAAioAAB4AAgIAAHYAAzMAAAcAAw4AAHEBBzoAAAEABwoAAIcADLwAABYADDkAAGAAAi0AAAYAAgEAABQAAgMAAHQAA0oAAG8BBzcAAAgABwcAAIYADL8AAAwADAEAAAQADD8AAF0AAjQAABQAAgMAAHQAA0oAAG4BBzcAAAwABwQAAIYADMIAAAYADEgAAFwAAjQAABQAAgMAAHQAA0oAAG4BBzUAABAABwMAAIUADBEBAFoAAjYAABIAAgQAAHQAA0sAAGwBBzMAABQABwIAAIUADBIBAFkAAjYAABAAAgUAAHUAA0sAAGwBBzIAABUABwQAAIMADBIBAFkAAjYAABAAAgUAAHUAA0sAAGwBBzIAABUABwQAAIMADK4AAAwADFkAAFgAAjgAAA0AAgYAAHUAA0sAAGoBBzQAABYABwMAAIMADJ4AAC0ADEkAAFYAAj0AAAcAAggAAHUAA0wAAGgBBzUAABYABwQAAIIADBsAAAQADHcAAD4ADEIAAFQAAkwAAHUAA0wAAGgBBzQAABgABwMAAIEADBkAAAsADG0AAEwADDsAAFMAAksAAHcAA0sAAGcBBzIAAB0ABwEAAIEADBgAAA4ADGUAAFgADDYAAFIAAksAAHcAA0sAAGYBBzIAAB4ABwIAAIAADBcAABIADF0AAGMADDAAAFIAAksAAHcAA00AAGMBBzIAAB8ABwIAAIAADBcAABIADF0AAGMADDAAAFIAAksAAHcAA00AAGMBBzIAAB8ABwIAAIAADBUAABYADFgAAGsADCwAAFEAAkoAAHoAA0sAAGIBBzMAAB8ABwIAAIAADBIAABoADFMAAHIADCoAAE8AAksAAHoAA0sAAGABBzUAAB8ABwMAAH8ADBIAABoADFAAAHoADCUAAE8AAksAAHsAA0oAAF8BBzYAACAABwIAAH8ADBEAABwADEsAAIIADCEAAE8AAkoAAHwAA0oAAF4BBzcAACAABwIAAH8ADBEAABwADEgAAIkADB4AAE4AAkoAAHwAA0sAAFwBBzgAACAABwIAAH8ADBEAAB4ADEQAAI8ADBoAAE4AAkoAAH0AA0oAAFsBBzkAACAABwMAAH4ADBEAAB4ADEQAAI8ADBoAAE4AAkoAAH0AA0oAAFsBBzkAACAABwMAAH4ADA8AACEADEAAAJUADBcAAE4AAkoAAH0AAwcAAAUAAz4AAFoBBzsAAB8ABwMAAH4ADA4AACMADD0AAJsADBIAAE8AAkgAAH8AAwYAAAgAAzwAAFcBBz4AAB4ABwQAAH4ADA4AACMADDkAAKMADA0AAE8AAkkAAIAAAwQAAAsAAzoAAFYBB0AAAB0ABwQAAH4ADA4AACQADDYAAKoADAUAAFIAAkkAAIAAAwMAAAwAAzoAAFUBB0UAABcABwcAAH0ADA0AACUADDQAAAMBAkkAAIAAAwMAAA4AAzgAAFMBB1AAAAwABwkAAH0ADA0AACUADDEAAAYBAkkAAIAAAwMAAA4AAzgAAFEBB1UAAAYABwwAAH0ADA0AACUADDEAAAYBAkkAAIAAAwMAAA4AAzgAAFEBB1UAAAYABwwAAH0ADA0AACQADDAAAAgBAkkAAIEAAwIAAA4AAzgAAE8BB2kAAH0ADAsAACYADCwAAFUACxcAAKAAAkkAAJEAAzkAAE0BB2oAAH0ADAoAACcADCoAAEsACzAAAJMAAkkAAJIAAzgAAEoBB20AAH4ADAgAACgADCgAAEYACz4AAIwAAkkAAJUAAzUAAEgBB28AAH4ADAgAACcADCYAAEMAC0sAAIUAAkkAAJgAAzIAAEYBB3EAAH4ADAgAACcADCYAAEMAC0sAAIUAAkkAAJgAAzIAAEYBB3EAAH4ADAcAACgADCQAAD8AC1YAAIAAAkkAAJkAAzEAAEMBB3QAAH4ADAcAACcADCIAAD8AC14AAHsAAkkAAJoAAzAAAEEBB3gAAH0ADAYAACcADB8AAD4AC2YAAHgAAkgAAJoAAzAAAD8BB3oAAH0ADAcAACYADB0AAD0AC20AAHQAAkgAAJoAAzAAADsBB34AAH0ADAcAACYADBkAAD0AC3QAAHEAAkgAAJsAAy8AAMoABxIAAF0AB4AAAH4ADAYAACYADBcAADwAC3sAAG0AAkgAAJwAAy4AAMAABycAAE4AB4QAAH4ADAYAACYADBcAADwAC3sAAG0AAkgAAJwAAy4AAMAABycAAE4AB4QAAH8ADAUAACYADBMAAD0AC4EAAGoAAkoAAJoAAy4AALwABzIAAEQAB4cAAH8ADAYAACMADBMAAD0AC4YAAGcAAkoAAJoAAy4AALgABz4AADcAB4wAAIEADAUAACEADBEAAD4AC4oAAGUAAkoAAH4AAwEAABsAAy4AALYAB0cAACoAB5IAAIIADAYAAA8ADAEAAA0ADA8AAD4AC5IAAGEAAkoAAH4AAwEAABoAAy4AALQAB1QAABcAB5sAAIIADAgAAAoADAYAAAkADA4AAD8AC5YAAGAAAkoAAH0AAwEAABoAAy4AALIABwgBAIQADCgAAEIAC5kAAF8AAkoAAH0AAwEAABoAAy4AALEABwkAAAcAB/cAAIYADCgAAEIAC5kAAF8AAkoAAH0AAwEAABoAAy4AALEABwkAAAcAB/cAAIcADCIAAEMAC58AAF0AAksAAHwAAwEAABkAAy8AAK4ABwsAAAkAB/YAAIoADBsAAEYAC6IAAFsAAksAAHsAAwQAABYAAzAAAK0ABwcAABMAB/EAAI4ADA8AAEoAC6cAAFoAAksAAHsAAwUAABQAAzEAAK0ABwYAABUAB/AAAOUAC6oAAFoAAksAAHoAAwYAAA4AAzYAAKwABwYAABcAB+8AAOMAC6wAAFoAAksAAHkAAw0AAAYAAzgAAKsABwcAABcAB+8AAOAAC7AAAFkAAkwAAHgAA0oAAKwABwYAABoAB+0AAOAAC7AAAFkAAkwAAHgAA0oAAKwABwYAABoAB+0AAN4AC7IAAFkAAk0AAHYAA0sAAKwABwUAABsAB+0AANwAC7QAAFoAAkwAAHYAA0sAAKsABwQAAB4AB+sAANoAC7gAAFkAAk4AAHIAA00AAKsABwMAACAAB+oAANcAC4kAAAgACyoAAFkAAk8AAHEAA00AAKsABwMAACAAB+oAANQAC4sAAAoACygAAFoAAk8AAHAAA0wAAK0ABwMAACEAB+kAANEAC4sAABEACyQAAFsAAk8AAG4AA00AAK0ABwMAACEAB+gAANIAC4sAABEACyQAAFsAAk8AAG4AA00AAK0ABwMAACEAB+gAANAAC4sAABUACyIAAFsAAh0AAAMAAjAAAG0AA00AAK0ABwMAACAAB+kAAMwAC44AABYACyEAAFwAAhkAAAkAAi8AAGsAA04AAK0ABwMAACAAB+kAAMoAC5AAABcACyAAAF4AAhYAAAwAAi0AAGoAA04AAK8ABwIAAB8AB+oAAMYAC5MAABgACx8AAF8AAhIAABMAAi0AAGYAA08AAK8ABwIAAB8AB+kAAMQAC5YAABkACx0AAGAAAhAAABYAAiwAAGQAA1EAAK8ABwMAAB4AB9UAAAQABxAAAMAAC5cAAB4ACxkAAGMAAg8AABcAAi0AAGEAA1EAALEABwQAABsAB9QAAAgABw4AAMAAC5cAAB4ACxkAAGMAAg8AABcAAi0AAGEAA1EAALEABwQAABsAB9QAAAgABw4AAL0AC5oAAB8ACxcAAGQAAg4AABgAAi4AAF8AA1IAALEABwUAABgAB9MAAA4ABwoAALoAC50AACAACxYAAGYAAg0AABoAAi0AAF0AA1MAALIABwUAABUAB9QAABEABwgAALUAC6IAACEACxMAAGgAAgwAABsAAi8AAFoAA1MAALMABwcAABMAB9QAABIABwYAALEAC6cAACEACxIAAGoAAgoAAB0AAi8AAFgAA1QAALQABwYAABMAB84AAAQABwEAABMABwYAAKwAC6wAACEACxAAAGwAAggAACAAAjAAAFQAA1YAALQABwYAABMAB8wAABoABwQAAK4AC6wAACEACxAAAGwAAggAACAAAjAAAFQAA1YAALQABwYAABMAB8wAABoABwQAAKgAC7IAACAACw8AAG4AAggAACAAAjEAAFEAA1cAALcABwQAABMAB8oAABwABwQAAKAAC7oAAB8ACw4AAHEAAgcAACAAAjQAAE0AA1gAALgABwMAABMAB8cAAB8ABwMAAJsAC8AAAB8ACw0AAHIAAgcAACEAAjQAAEoAA1kAALkABwMAABIAB8cAACAABwMAAJYAC8UAAB8ACwoAAHcAAgUAACAAAjgAAEQAA1wAALoABwMAABEAB8cAACAABwIAAJUAC8gAAB4ACwgAAHkAAgcAAB4AAjsAAD8AA1wAAL0ABwQAAA4AB8gAAB8ABwMAAJMAC8oAABwACwkAAHsAAgQAACAAAj0AADsAA14AAL4ABwYAAAoAB8cAACEABwIAAJQAC8oAABwACwkAAHsAAgQAACAAAj0AADsAA14AAL4ABwYAAAoAB8cAACEABwIAAJEAC84AABoACwcAAH4AAgYAAB4AAkAAADQAA2IAAL8ABwkAAAEAB8wAAB4ABwQAAJEAC9EAABcACwYAAIEAAgUAAB0AAkQAAC4AA2QAAMIAB9MAABwABwcAAI8AC9kAAAsACwEAAAIACwcAAIQAAgQAAB0AAkUAACsAA2UAAMQAB9IAABwABwYAAI8AC9wAAAcACwoAAIYAAgUAABsAAkcAACkAA2YAAMQAB9IAABwABwQAAI8AC+0AAIkAAgUAABgAAkoAACcAA2YAAMYAB9EAABwABwMAAI8AC+wAAIwAAgYAABUAAkwAACUAA2cAAMcAB9AAABsABwQAAI8AC+wAAIwAAgYAABUAAkwAACUAA2cAAMcAB9AAABsABwQAAI4AC+oAAI8AAgsAABEAAksAACUAA2YAAMkAB9AAABoABwMAAI4AC+kAAJMAAggAABIAAk0AACIAA2cAAMsAB84AABgABwQAAI8AC+gAAJUAAgcAABIAAk0AACIAA2YAAM4AByEAAAIAB6MAAB0ABwQAAI8AC+cAADIACgwAAFkAAgcAABQAAksAACAAA2gAAM8ABx0AAAkAB5sAACAABwQAAI8AC+UAADEAChMAAFcAAgYAABUAAkoAACAAA2YAANIABxoAAA0AB5gAACAABwMAAJEAC+QAAC8AChcAAFcAAgUAABUAAjUAAAIAAhMAACAAA2UAANQABxcAABAAB5cAABsABwcAAJIAC+QAAC8AChcAAFcAAgUAABUAAjUAAAIAAhMAACAAA2UAANQABxcAABAAB5cAABsABwcAAJIAC+IAAC8AChwAAFUAAgUAABQAAjIAAAcAAhIAAB8AA2UAANYABxUAABEAB5YAABIABwEAAAYABwcAAJIAC+EAAC8ACiAAAFUAAgQAABMAAjIAAA0AAg0AAB8AA2QAANgABxIAABMAB5QAABQABw0AAJMAC98AAC8ACiMAAFQAAgcAABAAAi8AABEAAgwAAB8AAykAAAYAAzQAANsABw8AABUAB5MAABQABwwAAJMAC98AACwACigAAFUAAgcAAAQAAgEAAAYAAjAAABQAAgsAAB8AAycAAAsAAzAAAN0ABw0AABYAB5IAABUABwkAAJYAC9wAAC0ACioAAFYAAg4AAAEAAjEAABUAAgoAACIAAyMAABAAAy0AAN4ABwwAABsAB40AABUABwcAAJgAC9oAAC0ACi0AAFYAAj8AABYAAgkAACIAAyAAABYAAykAAOIABwgAAB0AB40AABMABwcAAJkAC9oAAC0ACi0AAFYAAj8AABYAAgkAACIAAyAAABYAAykAAOIABwgAAB0AB40AABMABwcAAJgAC9oAAC0ACjAAAFUAAj0AABcAAgkAACIAAyAAABYAAycAAOUABwcAAB4AB4wAABEABwYAAJsAC9gAACwACjQAAFUAAjsAABoAAgcAACIAAx8AABgAAyUAAOgABwUAAB4AB40AAA4ABwUAAJ4AC9YAACwACjYAAFUAAjsAABsAAgYAACMAAx0AABkAAyUAAOkABwUAAB8AB4wAAAoABwUAAKEAC9QAACsACjoAAFUAAjkAABwAAgYAACMAAxwAABoAAyQAAO0ABwIAAB8AB5EAAAMABwMAAKQAC9MAACsACjwAAFcAAjcAAB0AAgUAACMAAxsAABwAAyIAAO8ABwIAAB8AB5IAAKgAC9MAACsACjwAAFcAAjcAAB0AAgUAACMAAxsAABwAAyIAAO8ABwIAAB8AB5IAAKgAC9IAACsACj4AAFcAAjYAAB0AAgMAACUAAxsAAB0AAyAAABEBB4sAAK8AC88AACwACkEAAFcAAjAAACIAAgMAACUAAxoAAB4AAx8AABEBB4MAALgACxwAAAUAC60AACoACkQAAFgAAi0AACMAAgQAACYAAxkAAB4AAx0AABMBB3kAAMIACxoAAAkAC6oAACkACkcAAFgAAigAACcAAgQAACYAAxYAACIAAxsAAP0ABwcAAA4AB3MAAMkACxkAAA0AC6YAACkACkkAAFkAAiYAACcAAgQAACcAAxUAACMAAxoAAP8ABwgAAAsAB3AAAM0ACxYAABMAC6EAACkACk0AAFoAAiIAACkAAgMAACgAAxMAACgAAxUAAAMBBwYAAAcAB20AANMACxYAABMAC6EAACkACk0AAFoAAiIAACkAAgMAACgAAxMAACgAAxUAAAMBBwYAAAcAB20AANMACxUAABYAC50AACkACk8AAFsAAiAAACoAAgMAACgAAxMAACsAAxEAAAYBB3MAANgACxQAABgAC5sAACgAClEAAFwAAh0AACwAAgMAACgAAxMAAC4AAw0AAAsBB2oAAN0ACxIAABsAC5kAACYAClUAAFwAAhsAAC0AAgIAACoAAxIAAC4AAwsAAA8BB2UAAOAACxIAABsAC5YAACgAClYAAF0AAhkAAC4AAgIAACoAAxIAAC8AAwkAABQBB10AAOQACxEAAB4AC5MAACcAClgAAGAAAhUAAC4AAgMAACoAAxIAAC8AAwgAABcBB1gAAOcACxAAACAAC5EAACcACloAAGAAAhQAACwAAgQAAC0AAxEAABsAAwEAABIAAwcAABsBB1IAAOoACxAAACAAC5EAACcACloAAGAAAhQAACwAAgQAAC0AAxEAABsAAwEAABIAAwcAABsBB1IAAOoACw8AACIAC44AACYACl0AAGEAAhMAACoAAgYAAC0AAxEAABoAAwIAABMAAwUAACABB0sAAO0ACw8AACMAC4wAACUACl8AAGQAAhAAACUAAgoAAC4AAxIAABgAAwMAABIAAwQAACUBB0MAAPIACw4AACUAC4kAACYACmAAAGUAAhAAACYAAggAAC8AAxQAABYAAwIAABIAAwIAACwBBzsAAPUACw4AACUAC4gAACQACmQAAGYAAg4AACcAAgcAAC8AAxQAABYAAwMAABAAAwIAADIBBzAAAPsACw4AACUAC4YAACUACmUAAGcAAg0AACcAAgYAADEAAxMAABcAAwQAAAwAAwMAADkBByQAAP8ACxAAACUAC4UAACQACmcAAGoAAgoAACcAAgYAADEAAxEAABkAAwYAAAgAAwQAAEcBBwkAAA0BCxAAACUAC4UAACQACmcAAGoAAgoAACcAAgYAADEAAxEAABkAAwYAAAgAAwQAAEcBBwkAAA0BCxAAACUAC4MAACUACmgAAGwAAgkAACYAAgQAADQAAxAAABkAAw8AAGACCw0AACgAC4IAACMACmwAAGwAAggAACYAAgQAADQAAxAAABkAAw4AAGECCwwAACgAC1AAAAYACywAACMACm0AAG4AAgkAACMAAgMAADYAAw8AABgAAw0AAGMCCwsAACkAC08AAAkACykAACIACm8AAHEAAggAACAAAgMAADcAAw8AABgAAwwAAGYCCwgAACoAC0wAAA0ACyYAACMACnAAAHMAAggAAAwAAgEAAA8AAgUAADgAAxAAABYAAwoAAGgCCwgAACkAC0sAABMACyAAACQACnEAAHUAAhQAAAwAAgYAADkAAxAAABYAAwgAAGoCCwgAACkAC0sAABMACyAAACQACnEAAHUAAhQAAAwAAgYAADkAAxAAABYAAwgAAGoCCwcAACkAC0sAABYACx0AACMACnMAAHkAAhQAAAIAAgsAADwAAw4AABUAAwgAAGsCCwYAACkAC0sAABcACxwAACIACnUAAHwAAh0AAD4AAw8AABIAAwcAAG0CCwYAACQAC04AABoACxoAACIACnYAAIAAAhcAAEEAAxAAAAwAAwgAAHACCwYAACEAC1EAABoACxgAACMACncAAIQAAhEAAEMAAxQAAAYAAwgAAHICCwYAABkAC1gAABwACxUAACQACnkAAIgAAgcAAEkAAx8AAHQCCwYAABgAC1cAAB8ACxMAACIACnwAANkAAxsAAHcCCwYAABgAC1cAAB8ACxMAACIACnwAANkAAxsAAHcCCwYAABgAC1YAACIACxAAACIACn0AANwAAxYAAHkCCwcAABYAC1cAACIACw8AACIACn0AAN4AAxEAAH0CCwcAABUAC1YAACUACwwAACMACn4AAOEAAwsAAIACCwkAABIAC1cAACUACwoAACQACn8AAGwDCwsAAAwAC1sAACQACwoAACMACoEAAGwDCwsAAAwAC1sAACQACwoAACMACoEAAG0DCw8AAAUAC18AACIACwkAACIACoMAAG0DC3MAACAACwoAACIACoQAAG0DC3MAACAACwgAACMACoUAAG0DC3MAACAACwYAACQACoYAAG0DC3MAAB8ACwYAACMACogAAG0DC3MAAB8ACwQAACQACnwAAAQACgMAAAQACgIAAG0DC3MAAB8ACwQAACQACnwAAAQACgMAAAQACgIAAG0DC3QAAB0ACwQAACQACn0AAAUACgEAAAUACgIAAG4DC3UAABkACwMAACYACncAAAUACgIAAAsACgIAAG4DC3YAABUACwUAACYACncAAAcACgEAAHsDC3gAAA8ACwcAACUACnoAAIMDC30AAAcACwkAACUACn4AAIEDC4kAACcACnwAAIQDC4kAACcACnwAAIQDC4gAACcACnsAAIYDC4YAACgACnwAAIYDC4MAACgACnoAAIwDC4EAACgACnsAAIwDC38AACkACnsAAI0DC30AACoACn8AAIoDC30AACoACn8AAIoDC3oAACoACoAAAI4DC3YAACsACoAAAI8DC3QAACwACn8AAJEDC3AAAC4ACn4AAJUDC20AAC8ACn8AAJUDC2oAADAACoUAAJEDC2oAADAACoUAAJEDC2cAADEACoYAAJMDC2MAADMACoUAAJUDC2AAADQACoUAAJcDC1wAADYACoYAAJkDC1kAADYACogAAJkDC1kAADYACogAAJkDC1YAADgACokAAAMACgIAAJQDCxoAAAYACzIAADkACowAAAIACgMAAJUDCxYAAAsACy4AADkACpEAAJcDCxMAABIACyYAADwACpQAAJYDCxEAABQACyIAAD0ACpYAAJYDCxAAABYACx4AAD0ACpcAAJgDCxAAABYACx4AAD0ACpcAAJoDCw4AABYACxwAAD4ACpgAAJoDCwwAABkACxkAAD4ACpgAAJ0DCwoAABsACxUAAD4ACpoAAJ4DCwgAAB4ACxIAAD4ACpwAAJ8DCwcAAB4ACxEAAD0ACqAAAJ0DCwcAACAACwwAAD0ACqIAAJ4DCwcAACAACwwAAD0ACqIAAJ8DCwUAACEACwoAAD0ACqMAAKADCwUAACEACwkAADwACqQAAKIDCwUAAB4ACwkAADoACqgAAKMDCwQAAB4ACwcAADoACqkAAKQDCwQAAB4ACwYAADgACqwAAKYDCwIAAB0ACwUAADcACrAAAAIACgEAAP0ACQYAAJ8CCwIAAB0ACwUAADcACrAAAAIACgEAAP0ACQYAAKACCwIAABwACwQAADYACrUAAPgACREAAJsCCwIAABoACwQAADMACrcAAPUACRoAAJgCCwIAABcACwMAADQACrgAAPIACSAAAJcCCwcAAAwACwcAADEACrwAAPAACSQAAJYCCwkAAAcACwcAADAACr4AAO8ACScAAJcCCxQAAC4ACsIAAOsACSwAAJUCCxQAAC4ACsIAAOsACSwAAJcCCw8AAC4ACsUAAOkACS8AAJkCCwcAADEACsYAAOkACTEAAMwCCsgAAOoACTMAAMkCCsoAAOcACTYAAMYCCs0AAAQACgEAAOEACTgAAMMCCtUAAN8ACTsAAMECCtUAAN8ACTsAAMACCr8AAAcACg8AAN4ACT0AAL0CCsAAAAwACgwAANwACUAAALoCCsAAABAACgkAANwACUEAALkCCsEAABEACgcAANwACUMAALcCCsEAABIACgcAANsACUQAALcCCsEAABIACgcAANsACUQAALYCCsIAABIACgYAANsACUYAALICCr8AABgACgQAANwACUcAALECCr4AABoACgMAANsACUkAALECCr0AABsACgMAANoACUsAAK8CCr4AABsACgIAANoACUwAAK4CCr4AABwACgEAANoACU0AAK4CCr4AABwACgEAANoACU0AAK4CChMAAAcACqIAAPgACU8AAKwCChIAAAwACp8AAPcACVAAAKwCCg8AABEACpwAAPYACVIAAKwCCg4AABQACpoAAPUACVUAAKoCCgwAABYACpoAAPQACVYAAKgCCg4AABcACpoAAPIACVcAAKgCCg4AABcACpoAAPIACVcAAKgCCgwAABkACpoAAPEACVkAAKkCCgkAABsACpkAAO8ACVsAAKkCCggAAB0ACpgAAO4ACVwAAKkCCggAAB0ACpoAAOsACV0AAKkCCggAAB0ACpsAAA8ACgIAANkACV4AAKkCCgcAAB0ACp8AAAYACgYAANkACV8AAKkCCgcAAB0ACp8AAAYACgYAANkACV8AAKkCCggAABwACqoAANkACQoAAAIACVQAAKoCCgYAABwACqoAANkACQgAAAgACVIAAKkCCgcAABsACqkAANgACQkAAAoACVEAAKoCCgYAABsACqgAANgACQYAABIACU0AAKsCCgYAABkACqcAANoACQQAABYACUsAAEYBCAkAAFwBCgcAABcACqcAANoACQQAABgACUsAAEEBCBIAAFcBCgcAABcACqcAANoACQQAABgACUsAAEEBCBIAAFgBCgoAABMACqYAANoACQUAABgACUsAAD8BCBkAAFUBCggAABMACqUAANoACQQAABoACUwAAD0BCB0AAFMBCgcAABMACqQAANoACQQAABwACUsAADwBCCIAAFABCgYAABEACqQAANoACQUAACAACUgAADkBCCgAAE4BCgYAABAACqMAANsACQQAACIACUcAADgBCC0AAEoBCgYAABAACqMAANsACQQAACIACUcAADgBCC0AAEsBCgYAAA4ACqMAANsACQUAACIACUkAADQBCDEAAEoBCgkAAAcACqUAANsACQYAACIACUkAADMBCDYAAEgBCgkAAAIACqcAANsACQcAACIACUoAAC8BCDsAAEcBCrAAANwACQUAACUACUkAAC0BCEAAAEUBCq0AAN0ACQQAACgACUgAACkBCEcAAEMBCqsAAN0ACQQAACoACUgAACUBCEwAAEEBCqsAAN0ACQQAACoACUgAACUBCEwAAEIBCqkAAN4ACQMAAC0ACUYAACABCFMAAEIBCqUAAN4ACQUAAC0ACUcAABcBCF4AAEABClQAAAkACkYAAN4ACQYAAC0ACUcAABMBCGUAAD8BClEAAAwACkIAAN8ACQYAAC4ACUgAABABCGoAAD0BCk8AAA4ACkAAAOAACQYAAC4ACUgAAA4BCG0AAD0BCkkAABYACjwAAOAACQcAAC4ACUkAAAoBCHIAADsBCkkAABYACjwAAOAACQcAAC4ACUkAAAoBCHIAAD4BCkQAABsACjcAAOEACQkAACsACU0AAAcBCAwAAAgACGEAAD0BCkIAAB0ACjUAAOIACQkAACsACU0AAAYBCAwAAAwACGEAADwBCkAAAB0ACjMAAOMACQsAACkACU8AAAMBCAoAABIACGAAADwBCj0AACAACjAAAOMACRIAAAkACQQAAAcACQUAAAkACVEAAAIBCAoAABQACGEAADwBCjsAACAACi8AAOQACRQAAAQACW4AAP8ACAsAABUACGQAADsBCjgAACIACi0AAOQACYcAAP4ACAwAABYACGQAADoBCjgAACIACi0AAOQACYcAAP4ACAwAABYACGQAADwBCjQAACUACikAAOcACYgAAPwACAwAABcACGUAADwBCjIAACgACiYAAOcACYoAAPoACAoAABsACGYAAD0BCi8AACgACiQAAOkACYsAAPgACAoAAB4ACGYAAD0BCisAACoACiMAAOkACYwAAPUACA0AAB4ACGcAAD0BCioAACoACiAAAOwACY4AAPIACA4AAB8ACGgAAD4BCicAACoACh4AAO0ACZAAAPAACA8AAB8ACGkAAD0BCicAACoACh4AAO0ACZAAAPAACA8AAB8ACGkAAD8BCiUAACoAChwAAO4ACZEAAO8ACBAAAB4ACGsAAEABCiUAACYAChsAAPEACZIAAOwACBIAAB4ACG0AAEIBCiEAACYAChoAAPAACZUAAOkACBQAABwACHAAAEMBCh8AACYAChcAAPMACZYAAOcACBUAABwACHEAAEUBChwAACUAChYAAPQACZcAAOYACBcAABsACHIAAEcBChkAACUAChQAAPYACZkAAOMACBoAABgACHQAAEYBChkAACUAChQAAPYACZkAAOMACBoAABgACHQAAEgBChgAACMAChIAAPkACZkAAOIACBwAABUACHcAAEsBChUAACEAChAAAPsACZgAAOMACCMAAAoACH4AAEwBChMAAB0AChAAAP4ACZcAAOIACCcAAAYACIEAAE8BChIAABUAChEAAAEBCZgAAOIACK8AAFMBChYAAAoACg8AAAUBCZsAAN4ACLAAAFMBChYAAAoACg8AAAUBCZsAAN4ACLAAAFgBCiUAAAkBCZwAAN0ACLIAAGABChUAABABCZ0AANsACLQAAIQCCZ0AANsACKMAAAQACA0AAIICCaAAANkACKEAAAoACAsAAIECCZ8AANoACJ8AAA8ACAoAAH8CCZ8AANgACJ8AABIACAkAAH8CCZ8AANgACJ8AABIACAkAAH4CCaAAANgACJ4AABUACAgAAH0CCaAAANgACJ4AABYACAcAAH0CCaAAANcACJ0AABgACAgAAHwCCXgAAAgACSAAANcACJsAABsACAcAAHsCCXgAAAoACR8AANcACJoAAB0ACAcAAHoCCXUAABEACRwAANUACJsAAB4ACAYAAHoCCXUAABEACRwAANUACJsAAB4ACAYAAHoCCXMAABQACRsAANUACJsAAB4ACAcAAHkCCXIAABYACRoAANUACJsAAB8ACAYAAHkCCXEAABgACRgAANYACJoAACAACAcAAHcCCXIAABgACRgAANYACJgAACEACAgAAHcCCXAAABoACRcAANYACJgAACMACAkAAHUCCW8AAB4ACRQAANYACJgAACUACAcAAHUCCW8AAB4ACRQAANYACJgAACUACAcAAHUCCW4AAB8ACRQAANYACJcAACcACAYAAHUCCW0AACEACRMAANYACJcAACcACAYAAHUCCW0AACEACREAANgACJgAACcACAYAAHQCCW0AACEACREAANgACJgAACcACAYAAHQCCW0AACEACREAANgACJgAACYACAcAAHQCCW0AACAACREAANkACJkAACUACAgAAHMCCW0AACAACREAANkACJkAACUACAgAAHMCCW0AACAACRAAANoACJsAACMACAgAAHICCRMAAAQACVcAACAACRAAANsACJwAACEACAgAAHICCREAAAoACU4AACUACQ8AANwACJ4AAB4ACAkAAHICCQ8AAA4ACUsAACQACRAAAN0ACKkAABEACAsAAHICCQ0AABEACUkAACQACQ8AAN8ACKoAAA8ACA0AAHECCQ0AABEACUkAACQACQ8AAN8ACKoAAA8ACA0AAHICCQkAABUACUcAACQACRAAAN8ACBsAAAUACIwAAAkACBEAAHICCQkAABUACUMAABIACQEAABMACRAAAOEACBkAAAkACKQAAHICCQgAABgACUAAABMACQQAAAoACRQAAOQACBQAAA8ACKIAAHICCQgAABkACT8AABMACQcAAAUACRIAAOgACBMAABMACJ8AAHICCQYAABwACT4AABQACQwAAPkACBEAABYACJ4AAHICCQYAABwACTwAABYACQgAAP4ACBAAABYACJ4AAHICCQYAABwACTwAABYACQgAAP4ACBAAABYACJ4AAHICCQUAAB0ACTsAABcACQYAAAABCBAAABcACJ0AAHICCQUAAB4ACTgAABkACQMAAAMBCA8AABgACJ0AAHMCCQQAAB0ACTkAABgACQMAAAYBCAsAABsACJwAAHMCCQUAABwACTkAABcACQIAAAgBCAoAABwACJwAAHMCCQQAABwACToAABQACQQAAAkBCAkAAB0ACJwAAHMCCQQAABwACToAABQACQMAAAsBCAgAACAACJkAAHMCCQQAABwACToAABQACQMAAAsBCAgAACAACJkAAHMCCQUAABoACTsAABQACQEAAA0BCAgAACEACJgAAHQCCQQAABgACT8AACEBCAgAACAACJgAAHQCCQUAABYACUAAACEBCAgAACAACJgAAHQCCQYAABQACUMAACABCAcAACAACJgAAHQCCQcAABIACUYAAAYACQYAABIBCAcAACAACJcAAHYCCQsAAAgACVcAABMBCAcAAB8ACJcAAHYCCQsAAAgACVcAABMBCAcAAB8ACJcAAHYCCQ8AAAEACVkAABQBCAkAABwACJgAAHYCCWkAABYBCAoAABcACJoAAHgCCWcAABYBCAsAAAoACAMAAAcACJwAAHgCCWYAABgBCLoAAHgCCWYAABkBCLgAAHoCCWUAABkBCLgAAHoCCWUAABkBCLgAAHoCCWUAABoBCLcAAHsCCWIAAB0BCLUAAHwCCWIAAB0BCLUAAH0CCWEAAB4BCLQAAH0CCWMAAB4BCLIAAH4CCWIAAB4BCLAAAIACCWIAAB4BCLAAAIACCWIAAB8BCK8AAIICCWAAACABCK0AAIMCCWAAACEBCKwAAIQCCWAAACEBCKoAAIUCCWAAACEBCKoAAIUCCWAAACEBCKoAAIYCCV8AACIBCKkAAIcCCV8AACMBCKYAAIgCCV8AACQBCKUAAIkCCT4AAAkACRgAACQBCKMAAIsCCTwAAAsACRgAACQBCKEAAI4CCTkAAA4ACRYAACUBCKAAAI4CCTkAAA4ACRYAACUBCKAAAI4CCTQAABUACRUAACUBCJ0AAJECCTIAABgACRUAACUBCGIAAAsACC4AAJICCTAAABoACRQAACYBCF8AAA4ACCwAAJQCCS8AABsACRMAACcBCF0AABEACCkAAJYCCS0AABwACRQAACcBCFgAABUACCkAAJYCCSwAAB4ACRMAACgBCFYAABcACCcAAJcCCSwAAB4ACRMAACgBCFYAABcACCcAAJgCCSgAACIACRIAACsBCFIAABsACCMAAJsCCSUAACMACRIAACwBCFEAAB0ACCAAAJ0CCSQAACQACRIAACwBCE4AAB8ACB4AAKACCSMAACQACRIAAC0BCE0AAB8ACB0AAKICCSIAACQACRIAAC4BCEsAACEACBsAAKUCCSAAACQACREAADIBCEYAACQACBkAAKYCCSAAACQACREAADIBCEYAACQACBkAAKgCCR4AACQACREAADMBCEQAACUACBgAAKoCCR0AACMACRIAADQBCEMAACYACBYAAKwCCRwAACIACRMAADYBCEAAACcACBQAAK8CCRsAACIACRIAADkBCD4AACcACBMAALECCRsAACIACREAADsBCDwAACcACBEAALYCCRgAACIACQ8AAD8BCDoAACYACBEAALcCCRgAACIACQ8AAD8BCDoAACYACBEAALgCCRgAACEACQ8AAEABCDoAACUACA4AAL0CCRgAAB8ACQ4AAEQBCDcAACQACA4AAL8CCRkAABwACQ4AAEcBCDYAACMACAwAAMQCCRkAABkACQ0AAEoBCDQAACIACAwAAMcCCRwAABMACQ0AAE4BCDEAACEACAoAAMoCCRwAABMACQ0AAE4BCDEAACEACAoAAMwCCRoAABMACQwAAFIBCC4AAB0ACAwAANECCRgAABEACQoAAFgBCCsAABoACA0AANUCCRkAAAsACQsAAFwBCCoAABgACAsAANwCCSkAAGEBCCsAAA4ACA4AAOICCSMAAGgBCCoAAAgACA4AAOoCCRsAAHABCCkAAAEACA0AAO4CCRsAAHABCCkAAAEACA0AAPQCCRAAAHkBCC8AAIYECCYAAJIECBUAAP//AP//ADh+";

function decodeBase64ToBytes(b64: string): Uint8Array {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const lookup = new Uint8Array(256);
  for (let i = 0; i < chars.length; i++) {
    lookup[chars.charCodeAt(i)] = i;
  }
  let len = b64.length;
  if (b64.endsWith('==')) len -= 2;
  else if (b64.endsWith('=')) len -= 1;
  const bytes = new Uint8Array(Math.floor((len * 3) / 4));
  let p = 0;
  for (let i = 0; i < len; i += 4) {
    const b0 = lookup[b64.charCodeAt(i)];
    const b1 = lookup[b64.charCodeAt(i + 1)];
    const b2 = lookup[b64.charCodeAt(i + 2)];
    const b3 = lookup[b64.charCodeAt(i + 3)];
    bytes[p++] = (b0 << 2) | (b1 >> 4);
    if (p < bytes.length) bytes[p++] = ((b1 & 15) << 4) | (b2 >> 2);
    if (p < bytes.length) bytes[p++] = ((b2 & 3) << 6) | b3;
  }
  return bytes;
}

// Decompress grid into a flat Uint8Array (1200 * 900)
let cachedGrid: Uint8Array | null = null;

export function getRegionGrid(): Uint8Array {
  if (cachedGrid) return cachedGrid;

  const bytes = decodeBase64ToBytes(RLE_BASE64);
  const grid = new Uint8Array(REGION_GRID_WIDTH * REGION_GRID_HEIGHT);
  let writeOffset = 0;

  for (let i = 0; i < bytes.length; i += 3) {
    const val = bytes[i];
    const count = bytes[i + 1] | (bytes[i + 2] << 8);
    for (let c = 0; c < count; c++) {
      grid[writeOffset++] = val;
    }
  }

  cachedGrid = grid;
  return grid;
}

/**
 * Returns the month region (1..12) at the given Garden world coordinates,
 * or 0 if the coordinate is not plantable (water, road, landmark, stone, out of bounds).
 */
export function getRegionAtWorld(worldX: number, worldY: number): number {
  if (worldX < 0 || worldX >= GARDEN_WORLD_WIDTH || worldY < 0 || worldY >= GARDEN_WORLD_HEIGHT) {
    return 0;
  }

  const gx = Math.floor(worldX / REGION_GRID_SCALE);
  const gy = Math.floor(worldY / REGION_GRID_SCALE);

  if (gx < 0 || gx >= REGION_GRID_WIDTH || gy < 0 || gy >= REGION_GRID_HEIGHT) {
    return 0;
  }

  const grid = getRegionGrid();
  return grid[gy * REGION_GRID_WIDTH + gx];
}

/**
 * Returns true if the coordinate is on approved plantable grass.
 */
export function isPlantableGrass(worldX: number, worldY: number): boolean {
  return getRegionAtWorld(worldX, worldY) > 0;
}
