"""Crop supplied alpha artwork without color keys, resampling, or changed art pixels."""
import argparse
import hashlib
import json
import os
from pathlib import Path
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT/'Resources/Garden Flowers/Chamomile/chamomile_garden_abc_candidate.png'
DEST = ROOT/'mobile/src/components/garden/flower-density-sandbox/chamomile-components'
# Semantic ID, visible open heads, source rectangle, manually inspected soil/stem base.
ROWS = [
 ('single/upright_01',1,(45,30,190,238),(114,225)),
 ('single/leaning_01',1,(207,30,339,238),(273,225)),
 ('single/upright_02',1,(343,30,482,238),(412,225)),
 ('single/bud_01',0,(478,30,587,238),(538,225)),
 ('single/leaning_02',1,(588,30,756,238),(662,225)),
 ('single/tiny_01',1,(776,30,922,238),(850,225)),
 ('single/upright_03',1,(937,30,1071,238),(1016,225)),
 ('single/bud_02',0,(1072,25,1216,238),(1152,225)),
 ('single/bud_03',0,(1226,60,1343,238),(1272,225)),
 ('single/bud_04',0,(1352,40,1505,238),(1433,225)),
 ('small/bud_pair_01',1,(35,250,239,445),(147,426)),
 ('small/open_pair_01',2,(273,250,476,445),(376,428)),
 ('medium/airy_01',3,(522,250,759,445),(641,428)),
 ('medium/airy_02',3,(783,250,1015,445),(896,432)),
 ('small/open_pair_02',2,(1061,250,1259,445),(1157,428)),
 ('medium/airy_03',3,(1300,240,1525,439),(1410,432)),
 ('full/spreading_01',6,(30,447,319,702),(169,680)),
 ('full/upright_01',6,(340,447,640,710),(490,680)),
 ('full/spreading_02',7,(650,450,962,716),(811,686)),
 ('full/airy_01',9,(979,445,1264,714),(1115,690)),
 ('full/airy_02',6,(1260,438,1524,714),(1406,691)),
 ('foliage/leaves_01',0,(20,727,199,924),(112,902)),
 ('foliage/leaves_02',0,(200,700,380,924),(287,906)),
 ('foliage/leaves_03',0,(380,726,548,929),(463,911)),
 ('foliage/leaves_04',0,(550,748,738,930),(650,909)),
 ('foliage/ground_01',1,(741,764,924,934),(824,909)),
 ('foliage/ground_02',3,(926,750,1105,933),(1007,909)),
 ('foliage/ground_03',3,(1107,748,1310,935),(1210,909)),
 ('foliage/ground_04',1,(1311,750,1508,935),(1404,908)),
]

def extract(im, roi):
    crop = im.crop(roi)
    # Discard only remote, almost invisible alpha residue. Keep original RGBA
    # within three pixels of alpha >= 8, including every antialiased fine edge.
    support = crop.getchannel('A').point(lambda a: 255 if a >= 8 else 0).filter(ImageFilter.MaxFilter(7))
    isolated = Image.new('RGBA', crop.size)
    isolated.paste(crop, (0, 0), support)
    return isolated

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    im=Image.open(SOURCE); assert im.mode=='RGBA' and im.size==(1536,1024)
    # True background gaps, away from petals/stems; reject the previous opaque sheet.
    assert max(im.getpixel(p)[3] for p in [(190,80),(330,80),(750,80),(920,80),(1050,80),(300,240),(750,970)]) <= 2
    records=[]; bindings='// Generated by extractChamomileComponents.py; DEV review only.\nexport const COMPONENT_IMAGES: Record<string, number> = {\n'
    for component_id,heads,roi,root in ROWS:
        crop=extract(im,roi); offset=((512-crop.width)//2,500-crop.height)
        canvas=Image.new('RGBA',(512,512)); canvas.paste(crop,offset)
        asset=f'mobile/assets/garden/flowers/species/chamomile/components/{component_id}.png'; target=ROOT/asset
        record=dict(componentId=component_id,speciesCode='CHAMOMILE',category=component_id.split('/')[0],
            bloomCount=heads,canvasWidth=512,canvasHeight=512,
            anchorX=(offset[0]+root[0]-roi[0])/512,anchorY=(offset[1]+root[1]-roi[1])/512,
            defaultVisualScale=1,worldUnitsPerPixel=.105,status='APPROVED_S_CLASS_REFERENCE',asset=asset,
            sourceRect=list(roi),canvasOffset=list(offset),sourceGroundPoint=list(root),contentBounds=list(canvas.getbbox()))
        if args.check:
            assert Image.open(target).tobytes()==canvas.tobytes(), component_id
        else:
            target.parent.mkdir(parents=True,exist_ok=True); canvas.save(target)
        record['sha256']=hashlib.sha256(target.read_bytes()).hexdigest(); records.append(record)
        bindings+=f'  {json.dumps(component_id)}: require({json.dumps(os.path.relpath(target,DEST).replace(chr(92),"/"))}),\n'
    bindings+='};\n'
    manifest=dict(source=SOURCE.relative_to(ROOT).as_posix(),sourceSha256=hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        alphaIsolation=dict(supportThreshold=8,originalEdgePaddingPixels=3,noColorKey=True),components=records)
    data=json.dumps(manifest,indent=2)+'\n'
    if args.check:
        assert (DEST/'componentManifest.json').read_text()==data
        assert (DEST/'componentImages.ts').read_text()==bindings
    else:
        DEST.mkdir(parents=True,exist_ok=True); (DEST/'componentManifest.json').write_text(data); (DEST/'componentImages.ts').write_text(bindings)
    print(f'{len(records)} Chamomile components: source RGBA, transparent padding, soil anchors and manifest verified.')

if __name__=='__main__': main()
