"""DEV candidate extraction from the supplied RGBA V2 sheet, not art generation.
No color key, resizing, repainting or recoloring. Source alpha isolates the art;
three pixels of original edge alpha are retained around the visible silhouette.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
from PIL import Image, ImageFilter, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT/'Resources/Garden Flowers/Tulip/tulip_garden_component_sheet_v2.png'
DEST = ROOT/'mobile/src/components/garden/flower-density-sandbox/tulip-components'
# Semantic ID, family, bloom count (buds count as one), isolated sheet ROI, soil point.
ROWS = [
 ('single/pink_01','pink',1,(180,28,354,247),(280,233)),
 ('single/pink_02','pink',1,(367,30,524,247),(450,233)),
 ('single/yellow_01','yellow',1,(526,38,679,247),(599,235)),
 ('single/yellow_02','yellow',1,(684,48,863,247),(760,235)),
 ('single/bud_yellow_01','yellow',1,(879,70,1051,247),(958,235)),
 ('single/bud_pink_01','pink',1,(1070,42,1217,247),(1140,235)),
 ('single/bud_pink_02','pink',1,(1221,24,1353,247),(1282,235)),
 ('single/bud_yellow_02','yellow',1,(1355,44,1527,247),(1452,235)),
 ('small/pink_01','pink',2,(205,298,379,473),(290,456)),
 ('small/yellow_01','yellow',2,(383,276,573,473),(475,454)),
 ('small/mixed_01','mixed',2,(577,286,781,475),(685,456)),
 ('small/pink_02','pink',2,(782,310,920,474),(859,454)),
 ('small/yellow_02','yellow',2,(925,276,1077,473),(999,455)),
 ('small/pink_03','pink',2,(1079,281,1270,474),(1184,453)),
 ('medium/pink_dominant_01','pink-dominant',3,(168,519,377,717),(277,691)),
 ('medium/pink_dominant_02','pink-dominant',3,(389,504,605,717),(490,691)),
 ('medium/yellow_dominant_01','yellow-dominant',3,(625,506,851,717),(740,692)),
 ('medium/yellow_dominant_02','yellow-dominant',3,(853,523,1060,717),(959,691)),
 ('medium/pink_dominant_03','pink-dominant',3,(1066,506,1271,717),(1170,691)),
 ('full/yellow_dominant_01','yellow-dominant',5,(375,739,668,1007),(521,972)),
 ('full/pink_dominant_01','pink-dominant',5,(672,738,968,1007),(813,972)),
 ('full/pink_dominant_02','pink-dominant',5,(970,741,1268,1007),(1120,971)),
 ('foliage/leaves_01','green',0,(1290,268,1499,460),(1390,442)),
 ('foliage/ground_01','green',0,(1438,395,1525,472),(1483,458)),
 ('foliage/ground_02','green',0,(1325,472,1526,605),(1421,579)),
 ('foliage/leaves_02','green',0,(1291,600,1417,716),(1343,696)),
 ('foliage/ground_03','green',0,(1428,641,1525,716),(1478,701)),
 ('foliage/leaves_03','green',0,(1281,818,1503,970),(1393,949)),
]

def extract(im, component_id, roi, root):
    crop = im.crop(roi)
    alpha = crop.getchannel('A')
    # This removes only disconnected low-alpha sheet residue, never a green/pink color key.
    support = alpha.point(lambda a: 255 if a >= 8 else 0).filter(ImageFilter.MaxFilter(7))
    if component_id == 'medium/pink_dominant_01':
        # The heading ends at x=222; flower pixels begin to its right on these scanlines.
        ImageDraw.Draw(support).rectangle((0,0,222-roi[0],532-roi[1]),fill=0)
    # Select only the connected plant at its soil point. Adjacent sheet fillers or
    # a neighboring stem's leaf can enter an otherwise rectangular extraction ROI.
    rx,ry=root[0]-roi[0],root[1]-roi[1]
    seed=min(((x,y) for y in range(crop.height) for x in range(crop.width) if support.getpixel((x,y))),
             key=lambda p:(p[0]-rx)**2+(p[1]-ry)**2)
    ImageDraw.floodfill(support,seed,127)
    support=support.point(lambda value:255 if value==127 else 0)
    isolated = Image.new('RGBA',crop.size)
    isolated.paste(crop,(0,0),support)
    return isolated

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    im=Image.open(SOURCE)
    assert im.mode=='RGBA' and im.size==(1536,1024), 'Unexpected source sheet'
    records=[]; bindings="// Generated by extractTulipComponentsV2.py; DEV review candidates only.\nexport const COMPONENT_IMAGES: Record<string, number> = {\n"
    for component_id,family,blooms,roi,root in ROWS:
        crop=extract(im,component_id,roi,root)
        offset=((512-crop.width)//2,500-crop.height)
        canvas=Image.new('RGBA',(512,512));canvas.paste(crop,offset)
        asset=f'mobile/assets/garden/flowers/species/tulip/components/{component_id}.png'
        target=ROOT/asset
        record=dict(componentId=component_id,category=component_id.split('/')[0],dominantColorFamily=family,
            bloomCount=blooms,canvasWidth=512,canvasHeight=512,
            anchorX=round((offset[0]+root[0]-roi[0])/512,6),anchorY=round((offset[1]+root[1]-roi[1])/512,6),
            defaultVisualScale=1,worldUnitsPerPixel=.16,status='READY_FOR_REVIEW',asset=asset,
            sourceRect=list(roi),canvasOffset=list(offset),sourceGroundPoint=list(root),contentBounds=list(canvas.getbbox()))
        if args.check:
            existing=Image.open(target);assert existing.mode=='RGBA' and existing.size==(512,512)
            assert existing.tobytes()==canvas.tobytes(), f'Extraction differs: {component_id}'
        else:
            target.parent.mkdir(parents=True,exist_ok=True);canvas.save(target)
        record['sha256']=hashlib.sha256(target.read_bytes()).hexdigest()
        assert canvas.getchannel('A').getextrema()[0]==0 and canvas.getbbox() not in (None,(0,0,512,512))
        records.append(record)
        relative=os.path.relpath(target,DEST).replace('\\','/')
        bindings+=f'  {json.dumps(component_id)}: require({json.dumps(relative)}),\n'
    bindings+='};\n'
    manifest=dict(source=SOURCE.relative_to(ROOT).as_posix(),sourceSha256=hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        alphaIsolation=dict(supportThreshold=8,originalEdgePaddingPixels=3,noColorKey=True),
        excluded=[dict(sheetLocation='D/full leftmost',reason='Label text meets the left bloom; clean separate export required rather than risking petal damage')],
        components=records)
    data=json.dumps(manifest,indent=2)+'\n'
    if args.check:
        assert (DEST/'componentManifest.json').read_text()==data
        assert (DEST/'componentImages.ts').read_text()==bindings
    else:
        DEST.mkdir(parents=True,exist_ok=True)
        (DEST/'componentManifest.json').write_text(data)
        (DEST/'componentImages.ts').write_text(bindings)
    print(f'{len(records)} unique components: exact source RGBA retained inside isolated artwork; transparent canvases and metadata verified. One label-adjacent full cluster excluded.')

if __name__=='__main__':main()
