"""DEV extraction of supplied Hydrangea RGBA, without color keys or art alteration."""
import argparse
import hashlib
import json
import os
from pathlib import Path
from PIL import Image, ImageFilter, ImageDraw

ROOT=Path(__file__).resolve().parents[2]
SOURCE=ROOT/'Resources/Garden Flowers/Hydrangea/hydrangea_garden_abc_candidate.png'
DEST=ROOT/'mobile/src/components/garden/flower-density-sandbox/hydrangea-components'
# ID, source color, main head count, ROI, logical soil/stem base.
ROWS=[
 ('head/blue_compact_v2','blue',1,(965,6,1168,197),(1058,179)),
 ('head/pink_compact_v2','pink',1,(1171,18,1359,196),(1270,185)),
 ('head/lavender_side_v2','lavender',1,(1364,4,1507,202),(1387,181)),
 ('partial/blue_side_v2','blue',1,(22,188,164,329),(78,318)),
 ('partial/lavender_side_v2','lavender',1,(158,198,275,326),(227,309)),
 ('partial/lavender_open_v2','lavender',1,(402,193,548,333),(467,323)),
 ('partial/pink_budding_v2','pink',1,(925,182,1046,313),(970,297)),
 ('partial/blue_budding_v2','blue',1,(1135,195,1258,332),(1168,319)),
 ('bud/cream_side_v2','green',0,(270,184,406,331),(298,317)),
 ('bud/cream_branch_v2','green',0,(544,175,693,332),(576,313)),
 ('bud/green_side_v2','green',0,(696,187,838,326),(761,312)),
 ('bud/green_upright_v2','green',0,(832,209,930,333),(870,324)),
 ('bud/green_branch_v2','green',0,(1035,188,1148,334),(1063,321)),
 ('bud/cream_upright_v2','green',0,(1247,186,1407,335),(1330,322)),
 ('foliage/bud_branch_v2','green',0,(303,325,450,482),(352,468)),
 ('foliage/tall_leaf_v2','green',0,(459,311,563,481),(497,466)),
 ('foliage/side_leaves_v2','green',0,(556,319,674,491),(578,463)),
 ('foliage/flowering_branch_v2','green',0,(765,308,979,489),(908,466)),
 ('foliage/wide_branch_v2','green',0,(949,312,1142,483),(1069,468)),
 ('foliage/leaning_leaf_v2','green',0,(1146,332,1240,475),(1190,456)),
 ('foliage/tall_branch_v2','green',0,(1243,321,1396,493),(1326,479)),
 ('foliage/bud_fan_v2','green',0,(1387,371,1528,486),(1463,471)),
 ('asymmetric/blue_pink_v2','mixed',2,(20,477,289,690),(138,664)),
 ('asymmetric/lavender_companion_v2','lavender',2,(813,480,1003,682),(913,663)),
 ('asymmetric/blue_pink_side_v2','mixed',2,(999,455,1243,691),(1127,665)),
]

def extract(im,roi,root):
    crop=im.crop(roi)
    support=crop.getchannel('A').point(lambda a:255 if a>=8 else 0).filter(ImageFilter.MaxFilter(7))
    rx,ry=root[0]-roi[0],root[1]-roi[1]
    seed=min(((x,y) for y in range(crop.height) for x in range(crop.width) if support.getpixel((x,y))),
             key=lambda p:(p[0]-rx)**2+(p[1]-ry)**2)
    ImageDraw.floodfill(support,seed,127)
    support=support.point(lambda value:255 if value==127 else 0)
    isolated=Image.new('RGBA',crop.size);isolated.paste(crop,(0,0),support)
    return isolated

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    im=Image.open(SOURCE);assert im.mode=='RGBA' and im.size==(1536,1024)
    assert max(im.getpixel(p)[3] for p in [(220,10),(395,10),(790,10),(1530,400),(780,680),(900,5)])<=2
    records=[];bindings='// Generated by extractHydrangeaComponents.py; DEV review only.\nexport const COMPONENT_IMAGES: Record<string, number> = {\n'
    for component_id,color,heads,roi,root in ROWS:
        crop=extract(im,roi,root);offset=((512-crop.width)//2,500-crop.height)
        canvas=Image.new('RGBA',(512,512));canvas.paste(crop,offset)
        asset=f'mobile/assets/garden/flowers/species/hydrangea/components/{component_id}.png';target=ROOT/asset
        record=dict(componentId=component_id,speciesCode='HYDRANGEA',category=component_id.split('/')[0],
            colorFamily=color,bloomCount=heads,canvasWidth=512,canvasHeight=512,
            anchorX=(offset[0]+root[0]-roi[0])/512,anchorY=(offset[1]+root[1]-roi[1])/512,
            defaultVisualScale=1,worldUnitsPerPixel=.18,status='APPROVED_L_CLASS_REFERENCE',asset=asset,
            sourceRect=list(roi),canvasOffset=list(offset),sourceGroundPoint=list(root),contentBounds=list(canvas.getbbox()))
        if args.check: assert Image.open(target).tobytes()==canvas.tobytes(),component_id
        else: target.parent.mkdir(parents=True,exist_ok=True);canvas.save(target)
        record['sha256']=hashlib.sha256(target.read_bytes()).hexdigest();records.append(record)
        bindings+=f'  {json.dumps(component_id)}: require({json.dumps(os.path.relpath(target,DEST).replace(chr(92),"/"))}),\n'
    bindings+='};\n'
    data=json.dumps(dict(artVersion=2,source=SOURCE.relative_to(ROOT).as_posix(),sourceSha256=hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        alphaIsolation=dict(supportThreshold=8,originalEdgePaddingPixels=3,noColorKey=True),
        excluded=[dict(sheetLocation='bottom Full Variations and largest complete top-row heads',reason='Reference only; excluded from routine Journal recipes to avoid repeated spherical bushes')],
        components=records),indent=2)+'\n'
    if args.check:
        assert (DEST/'componentManifest.json').read_text()==data
        assert (DEST/'componentImages.ts').read_text()==bindings
        actual={p.relative_to(ROOT).as_posix() for p in (ROOT/'mobile/assets/garden/flowers/species/hydrangea/components').rglob('*.png')}
        assert actual=={c['asset'] for c in records}, 'Stale/rejected Hydrangea assets remain'
    else:
        DEST.mkdir(parents=True,exist_ok=True);(DEST/'componentManifest.json').write_text(data);(DEST/'componentImages.ts').write_text(bindings)
    print(f'{len(records)} unique Hydrangea components, original RGBA and soil anchors verified.')

if __name__=='__main__':main()
