"""Failure-isolated batch extraction using the established original-alpha method."""
import argparse
import hashlib
import json
import os
from io import BytesIO
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter
from batchFlowerSources import SPECS

ROOT=Path(__file__).resolve().parents[2]
DEST=ROOT/'mobile/src/components/garden/flower-density-sandbox/batch-components'

def extract_piece(im, roi, ground):
    # Connectivity uses alpha only, never RGB/color keys. Restore a three-pixel
    # original-RGBA fringe after selecting the plant; do not threshold output alpha.
    roi=(max(0,roi[0]-32),max(0,roi[1]-32),min(im.width,roi[2]+32),min(im.height,roi[3]+32))
    crop=im.crop(roi)
    support=crop.getchannel('A').point(lambda a:255 if a>=32 else 0)
    rx,ry=ground[0]-roi[0],ground[1]-roi[1]
    seed=min(((x,y) for y in range(crop.height) for x in range(crop.width) if support.getpixel((x,y))),
        key=lambda p:(p[0]-rx)**2+(p[1]-ry)**2)
    ImageDraw.floodfill(support,seed,127)
    support=support.point(lambda v:255 if v==127 else 0).filter(ImageFilter.MaxFilter(7))
    isolated=Image.new('RGBA',crop.size);isolated.paste(crop,(0,0),support)
    return isolated,roi

def run(check=False, specs=None, audit=None, write=True):
    audit=audit if audit is not None else json.loads((ROOT/'docs/flower-visuals/BATCH_SOURCE_AUDIT.json').read_text())
    records=[];species=[];failures=[];piece_skips=[]
    bindings='// Generated by extractBatchFlowerComponents.py; DEV neutral review only.\nexport const COMPONENT_IMAGES: Record<string, number> = {\n'
    for code,cls,form,source,pieces in SPECS if specs is None else specs:
        verified=next((r for r in audit['candidates'] if r['sourcePath']==source),None)
        if not verified or verified['backgroundStatus']!='GENUINE_TRANSPARENT':
            failures.append(dict(speciesCode=code,status='SKIPPED_INVALID_SOURCE',reason='Candidate failed source audit'));continue
        try:
            assert hashlib.sha256((ROOT/source).read_bytes()).hexdigest()==verified['sourceSha256'],'Source changed since audit'
            im=Image.open(ROOT/source);im.load()
            selected=[];pending=[]
            for semantic,roi,ground in pieces:
                try:
                    crop,roi=extract_piece(im,roi,ground);alpha=crop.getchannel('A')
                    edge=[alpha.crop((0,0,crop.width,1)),alpha.crop((0,crop.height-1,crop.width,crop.height)),
                        alpha.crop((0,0,1,crop.height)),alpha.crop((crop.width-1,0,crop.width,crop.height))]
                    assert max(e.getextrema()[1] for e in edge)<8,'Visible crop edge; do not clip art'
                    assert alpha.getbbox(),'No isolated artwork'
                    offset=((512-crop.width)//2,500-crop.height)
                    canvas=Image.new('RGBA',(512,512));canvas.paste(crop,offset)
                    component_id=f'{code.lower()}/{semantic}'
                    asset=f'mobile/assets/garden/flowers/species/{code.lower()}/components/batch/{semantic}.png'
                    target=ROOT/asset
                    encoded=BytesIO();canvas.save(encoded,format='PNG');png=encoded.getvalue()
                    if check:assert target.read_bytes()==png,f'Pixels differ: {asset}'
                    pending.append((target,png))
                    rec=dict(componentId=component_id,speciesCode=code,category=semantic.split('/')[0],
                        canvasWidth=512,canvasHeight=512,anchorX=(offset[0]+ground[0]-roi[0])/512,
                        anchorY=(offset[1]+ground[1]-roi[1])/512,defaultVisualScale=1,
                        worldUnitsPerPixel=.10 if code=='COREOPSIS' else .16 if code=='BIRD_OF_PARADISE' else .13 if code=='OLIVE' else {'S':.12,'M':.15,'L':.18}[cls],
                        contentBounds=list(canvas.getbbox()),asset=asset,sourcePath=source,sourceRect=list(roi),sourceGroundPoint=list(ground),canvasOffset=list(offset),
                        sha256=hashlib.sha256(png).hexdigest(),status='READY_FOR_REVIEW')
                    selected.append(rec)
                except Exception as error:
                    piece_skips.append(dict(speciesCode=code,componentId=semantic,reason=str(error)))
            assert any(c['category'] not in ('bud','foliage') for c in selected),'No usable complete flowering/branch component'
            if write and not check:
                for target,png in pending:target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(png)
            records.extend(selected)
            species.append(dict(speciesCode=code,flowerClass=cls,footprintRadius={'S':9,'M':12,'L':16}[cls],
                baseVisualScale=.9 if code=='OLIVE' else 1,morphology=form,sourcePath=source,status='READY_FOR_REVIEW',
                componentCount=len(selected),pieceCounts={'sparse':1,'normal':1,'full':2} if code in ('COREOPSIS','SUNFLOWER','BIRD_OF_PARADISE','OLIVE') else {'sparse':1,'normal':2,'full':3}))
        except Exception as error:
            if check:raise
            failures.append(dict(speciesCode=code,status='SKIPPED_INVALID_SOURCE',reason=str(error)))
    for c in records:bindings+=f'  {json.dumps(c["componentId"])}: require({json.dumps(os.path.relpath(ROOT/c["asset"],DEST).replace(chr(92),"/"))}),\n'
    bindings+='};\n'
    result=dict(species=species,components=records,skipped=failures,skippedPieces=piece_skips,
        alphaIsolation=dict(supportThreshold=32,originalEdgePaddingPixels=3,noColorKey=True,outputPixels='Original RGBA; no resampling or recoloring'))
    data=json.dumps(result,indent=2)+'\n'
    if check:
        assert (DEST/'componentManifest.json').read_text()==data
        assert (DEST/'componentImages.ts').read_text()==bindings
    elif write:
        DEST.mkdir(parents=True,exist_ok=True);(DEST/'componentManifest.json').write_text(data);(DEST/'componentImages.ts').write_text(bindings)
    if write:print(json.dumps(dict(successful=[(s['speciesCode'],s['componentCount']) for s in species],skipped=failures,skippedPieces=piece_skips),indent=2))
    return result

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');run(p.parse_args().check)
