"""Report-only PNG validation. --sync writes Metro bindings, never changes images/statuses.
Requires Pillow. Run --check before builds to detect stale bytes/metadata/bindings.
"""
import argparse
import hashlib
import json
import math
import os
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'mobile/src/components/garden/flower-visuals/gardenArtManifest.json'
BINDINGS = MANIFEST.parent / 'gardenArtBindings.generated.ts'
COMPOSITIONS = ('sparse', 'normal', 'full')
STATUSES = ('MISSING', 'NEEDS_GARDEN_ART_ADAPTATION', 'READY_FOR_REVIEW', 'APPROVED')

def validate_asset(root, species, composition, asset):
    errors, warnings = [], []
    def number(v):
        return isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)
    if composition not in COMPOSITIONS: errors.append('INVALID_COMPOSITION')
    if asset.get('status') not in STATUSES: errors.append('INVALID_STATUS')
    for key in ('anchorX', 'anchorY'):
        if not number(asset.get(key)) or not 0 <= asset[key] <= 1: errors.append('INVALID_' + key)
    if not number(asset.get('visualScale')) or asset['visualScale'] <= 0: errors.append('INVALID_VISUAL_SCALE')
    if (asset.get('canvasWidth'), asset.get('canvasHeight')) != (512, 512): errors.append('INVALID_CANVAS_METADATA')
    slug = species.lower()
    expected = f'mobile/assets/garden/flowers/species/{slug}/base/{slug}_garden_{composition}.png'
    if asset.get('asset') != expected: errors.append('NONCANONICAL_ASSET_PATH')
    path = (root / expected).resolve()
    if not path.is_relative_to((root / 'mobile/assets/garden/flowers/species').resolve()):
        errors.append('UNSAFE_PATH')
        return dict(errors=errors, warnings=warnings, sha256=None, exists=False)
    exists = path.is_file()
    digest = None
    if not exists:
        errors.append('FILE_MISSING')
    else:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        try:
            with Image.open(path) as im:
                if im.format != 'PNG': errors.append('NOT_PNG')
                if im.size != (asset.get('canvasWidth'), asset.get('canvasHeight')): errors.append('WRONG_DIMENSIONS')
                if 'A' not in im.getbands() and 'transparency' not in im.info: errors.append('NO_ALPHA')
                alpha = im.convert('RGBA').getchannel('A')
                bounds = alpha.getbbox()
                if bounds is None: errors.append('ALL_TRANSPARENT')
                if alpha.getextrema()[0] == 255: errors.append('OPAQUE_RECTANGLE')
                if bounds == (0, 0, im.width, im.height):
                    errors.append('TOUCHES_ALL_FOUR_EDGES')
                    warnings.append('Likely matte/background or edge-to-edge content; inspect manually')
                if bounds:
                    hist = alpha.histogram(); opaque = hist[255] / (im.width * im.height)
                    if opaque > .8: warnings.append('Suspicious high opaque coverage; inspect for baked matte/checkerboard')
        except (OSError, ValueError) as error:
            errors.append('UNREADABLE_IMAGE: ' + str(error))
    if asset.get('status') == 'APPROVED':
        if asset.get('anchorStatus') != 'REVIEWED': errors.append('ANCHOR_NOT_REVIEWED')
        if not digest or asset.get('reviewedSha256') != digest: errors.append('APPROVAL_HASH_MISMATCH')
    return dict(errors=errors, warnings=warnings, sha256=digest, exists=exists)

def binding_text(rows):
    text = '// Generated by validateGardenArt.py --sync. Never edit or approve here.\n'
    text += "import type { GardenAsset } from './flowerVisualTypes';\n"
    text += 'export const GARDEN_ART_BINDINGS: Record<string, { source: number; metadata: GardenAsset; sha256: string }> = {\n'
    for row in rows:
        a = row['metadata']
        if row['errors'] or a['status'] not in ('READY_FOR_REVIEW', 'APPROVED'): continue
        relative = os.path.relpath(ROOT / a['asset'], BINDINGS.parent).replace('\\', '/')
        text += f'  {json.dumps(a["asset"])}: {{ source: require({json.dumps(relative)}), metadata: {json.dumps(a)}, sha256: {json.dumps(row["sha256"])} }},\n'
    return text + '};\n'

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--sync', action='store_true')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--strict', action='store_true', help='Missing pending slots also fail')
    parser.add_argument('--json', action='store_true')
    args = parser.parse_args()
    rows, failures, seen = [], [], set()
    for species in json.loads(MANIFEST.read_text()):
        code = species['speciesCode']
        if code in seen: failures.append('Duplicate species: ' + code)
        seen.add(code)
        if set(species['gardenAssets']) != set(COMPOSITIONS): failures.append('Expected exactly three compositions: ' + code)
        for composition, asset in species['gardenAssets'].items():
            row = dict(speciesCode=code, composition=composition, metadata=asset,
                       **validate_asset(ROOT, code, composition, asset))
            rows.append(row)
            fatal = [e for e in row['errors'] if e != 'FILE_MISSING' or args.strict or asset['status'] in ('READY_FOR_REVIEW', 'APPROVED')]
            if fatal: failures.append(f'{code}/{composition}: {", ".join(fatal)}')
    expected = binding_text(rows)
    if args.sync:
        # Even on errors, clear obsolete bindings so invalid artwork cannot remain bundled.
        BINDINGS.write_text(expected, encoding='utf-8')
    if args.check and (not BINDINGS.exists() or BINDINGS.read_text(encoding='utf-8') != expected):
        failures.append('Stale Garden art bindings: run --sync and review changes')
    if args.json: print(json.dumps(rows, indent=2))
    else:
        print(f'{len(rows)} slots; {sum(r["exists"] for r in rows)} files; {sum(not r["errors"] for r in rows)} structurally valid; {len(failures)} build errors')
        print(f'{sum("FILE_MISSING" in r["errors"] for r in rows)} missing slots (expected during art preparation)')
        for row in rows:
            for warning in row['warnings']: print(row['speciesCode'], row['composition'], warning)
        for error in failures: print(error)
    return bool(failures)

if __name__ == '__main__': sys.exit(main())
