ALTER TABLE "FairyState"
ADD COLUMN "currentState" VARCHAR(32) NOT NULL DEFAULT 'IDLE',
ADD COLUMN "currentLocation" VARCHAR(32) NOT NULL DEFAULT 'GARDEN_CENTER',
ADD COLUMN "stateStartedAt" TIMESTAMP(3),
ADD COLUMN "nextTransitionAt" TIMESTAMP(3),
ADD COLUMN "lastActiveAt" TIMESTAMP(3);
