ALTER TABLE "Flower"
ADD COLUMN "variant" VARCHAR(32) NOT NULL DEFAULT 'standard',
ADD COLUMN "rarity" VARCHAR(16) NOT NULL DEFAULT 'COMMON',
ADD COLUMN "growthState" VARCHAR(32) NOT NULL DEFAULT 'BLOOMED',
ADD COLUMN "visualEffect" VARCHAR(32),
ADD COLUMN "season" VARCHAR(16),
ADD COLUMN "generationSeed" VARCHAR(64);

ALTER TABLE "EmotionResult"
ADD COLUMN "secondaryEmotion" VARCHAR(32),
ADD COLUMN "intensity" DOUBLE PRECISION;
